# Site Settings
title: Edward Nguyen
email: enguyen@uw.edu
description: User Experience Designer

# About Stuff
avatar: edward.png
about: <p><strong>I'm Edward Nguyen, a product designer from Seattle, WA</strong>. I focus on interaction design and information architecture. I'm currently finishing my last year of graduate school at the University of Washington. Thank you for stopping by!</p>

# Build Settings
markdown: kramdown
permalink: pretty

port: 4000

sass:
  sass_dir: assets/css
  style: :compressed