# Site Settings
title: Edward Nguyen
email: enguyen@uw.edu
description: User Experience Designer

# About Stuff
avatar: edward.png
about: <p>I'm Edward Nguyen, a UX designer from Seattle, WA. I focus on designing functional and elegant products through a user centered design process.</p>

# Build Settings
markdown: kramdown
permalink: pretty

port: 4000

sass:
  sass_dir: assets/css
  style: :compressed